### ISSUE TITLE
Enforce whitespace in multiline pattern (and comment?)

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#11]
Currently, we allow for a single white space to precede the value of a multiline pattern and comment.
It works like this:

```rust
# Test
# Longer comment
key =
 | Value
 | Longer value
```

This was meant to increases readability, and I believe it does achieve its goal, but the fact that it's conditional, causes problems on the parser level.

Things like this have to be considered:

```rust
key =
 | Value
 |Longer Value
 | And more

key =
 |Value
 |Longer Value
 | And more
```

The most intuitive solution would be to look-ahead and deduct if all lines have at least one whitespace, and then remove the single space from each line of the block.

But for the sake of simplicity, why don't we just start with enforcing a single space after each "|" for now.

We can always introduce a more sophisticated algorithm later with forward compatibility, but simplify our lives now, without any visible drawbacks (I did not see a single case where someone would prefer to not use the whitespace).

Same applies to comments.

**Comment by stasm** [comment]
This was fixed by #32.
