### ISSUE TITLE
Rules for normalizing multiline text

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#122]
Localizers should be in control of the contents _and_ the formatting of their translations. I'd like to define rules for normalizing multiline text in the runtime to eliminate the surprises caused by how the bindings might normalize text inherently.

Multiline text is currently parsed and stored in the AST with all its whitespace, with the exception of leading and trailing whitespace. This is helpful for serialization and I'd like to keep it that way.

At the same time, the Fluent spec doesn't mandate any normalization of the multiline text. A multiline translation showing up in an HTML UI will have all its newlines normalized to a single space. On the other hand, a multiline translation which is displayed with an `alert()` will preserve all its newlines verbatim.

**Comment by stasm** [comment]
> This is both backwards and forwards incompatible, right?

Or neither? If we only change the behavior of the runtime, the syntax would remain the same.

Or, we might want to introduce a new syntax for opting out of the default normalization.

> We don't have a strong list of examples by projects that drive this right now, and I'm not sure where this will pan out to be a problem. alert isn't really good UX in any way ;-)

That's because we're mostly an HTML-first organization. As soon as we step into other territories (Rust, C# and game engines, chat interfaces), the problem of translations being multiline where localizers only intended to format them nicely to fit on the screen becomes real and pressing.

**Comment by Pike** [comment]
As far as compat goes, we should read this as "can I use old files with new fluent and vice versa". Parsing is a step there, but restricting it to parsing doesn't represent the practical concerns which we need to address.

**Comment by stasm** [comment]
Sorry, I didn't get your last comment. Would you mind trying to rephrase?

**Comment by stasm** [comment]
For a comic relief, check out the [SO answer on how to write multiline strings in YAML](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210).

It's off-topic but it should serve as a warning that even with best intentions it's easy to create systems which users find very complex.

**Comment by stasm** [comment]
> The main drawback here is that in an HTML scenario, this still renders as a single line.

I think I'm starting to understand where our thinking differs: you seem to think about the end of the formatting pipeline, which is rendering, whereas my intent was to define the behavior of the bindings. Think `Localization.formatValue` in `fluent-dom`. The environment still controls the rendering which is totally fine in my book.

Then, there's parsing—do I understand correctly that we both agree to preserve as much of the message layout in the AST as possible?

> I think that we should use semantic comments instead, and signal the white-space significance from the developer to the localization tool, with project-wide defaults at some point.

I agree that we semantic comments will be very helpful here. We'll need them anyways to make tools and ultimately localizers aware that a given translation may or may not use custom HTML. It's not only about whitespace normalization: depending on whether the message is used in HTML or through raw JS, a custom `<em/>` might be OK or not.

I think I've had enough time to digest the feedback. My goal is to design something robust, modular and extensible. Thus, I propose a new plan:

  - Let's not define any additional multiline normalization in 0.7, nor in 1.0.
  - Let's make the AST store as much whitespace as possible (#162 will help here).
  - Let's leave it up to bindings and third-party tools to provide their own normalization strategies. 

For instance, a hypothetical `fluent-cli` bindings module for translating CLI apps could use the `fluent-normalize-markdown` module to normalize all translations. Files used by `fluent-cli` should have a `### @format markdown` semantic comment (resource-wide) to let tools know what kind of formatting is going to be performed on the translations.

In another example (I'm not saying we should do this; it's just an example), `fluent-dom` could run `formatValue` through a `fluent-normalize-singleline` module. Messages formatted imperatively from the JS code would then have their contents normalized to a single line, regardless of how many line breaks they had in the Fluent file. These messages would need to have a `# @format singleline` semantic comment attached to them, or to their group or resource.

This approach leaves the normalization up to the consumers by sticking to the principle of the least power. By storing the newlines in the AST, we allow the consumers to dicide _if_ they want to handle them in any particular manner. At the same time, this proposal emphasizes the importance of semantic comments (#139). Develoeprs and tool authors will need to rely on them anyways to convey information about the target environment in which translations will be displayed. The environment may define not only its own whitespace normalization, but also which features are even allowed in translations.

**Comment by stasm** [comment]
> I think I'm starting to understand where our thinking differs: you seem to think about the end of the formatting pipeline, which is rendering, whereas my intent was to define the behavior of the bindings.

A note to future self: this was an important realization, as it made my understand that in neither case does the multiline normalization belong to the low-level formatting, i.e. `MessageContext.format`.

**Comment by stasm** [comment]
Closing this as WONTFIX as per my above comments.
