### ISSUE TITLE
Rename NamedArgument to Option

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#124]
Named arguments have a simple design: they only allow numbers and strings as values. (In the future they might also accept booleans, see #104). This design limits their use to options passed into formatters:

    NUMBER($ratio, minimumFractionDigits: 2)

I'd like to rename them to `Options`.

**Comment by Pike** [comment]
I prefer the pairing of named and positional arguments. I also find `Options` to be misleading to those people who know this from the js world, where that is a single object, not a list of named arguments.

**Comment by stasm** [comment]
We agreed OTP that this isn't really needed. Closing.
