### ISSUE TITLE
Reference parser stores Message Comment as Standalone Comment if Message has errors.

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#143]
Extracting from https://github.com/projectfluent/fluent.js/issues/206:

This seems like breakage of the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) - the new behavior changes the semantic role of a bit of information encoded in FTL file depending on an error which doesn't hinder parsers ability to interpret the information. This means that if someone writes a comment meant to be attached to a message, and there's an error in the message, they may end up with a standalone comment.
Now, this is not very consequential right now, but there's nothing guaranteeing that we won't have some behaviors expected for standalone vs. message comments.
Of course once an error happens, we just try to salvage, but in this case we do know that the comment was meant to be attached to the message, and yet we choose to encode it as a standalone.

I believe we should change the behavior of the reference parser.

**Comment by stasm** [comment]
This is related to #132 which is also asking how much of a message we should try to salvage in case of syntax errors.

> Of course once an error happens, we just try to salvage, but in this case we do know that the comment was meant to be attached to the message, and yet we choose to encode it as a standalone.

As soon as we enter the error recovery territory, it's hard to make assumptions about what the localizer meant. I question whether we can confidently claim that _we know that the comment was meant to be attached to the message_. It's a good guess, but might also be a mistake by the localizer.

The rule of thumb for the error recovery that I'd like to suggest, is to salvage as much as possible without risking that other messages or terms are affected. In other words, if a syntax error in one message could end up splitting the message in two and changing the value of the message before it, that's not a good error recovery strategy.

Comments are harmless to the UI and they don't impact translations in any way. I think we should try to salvage as much as we can here, which is what the reference parser currently does.

**Comment by Pike** [comment]
What stas said (which is basically what I also said in 206).

Also, as you type a new message in an ftl file, you'd get a weird user experience, if you'd:
1. start writing a comment - everything looks good
2. start a new line for your message - everything looks good
3. start the message by typing in the ID - the comment that was OK just turned into a syntax error
4. you need to get all the way to having the first parts of a value, and then it looks OK again
5. you start a placable by typing `{}`, and the comment is a syntax error again

**Comment by stasm** [comment]
> I'd also like to see my concern addressed - the behavior sets a precedence - the parser knowingly introduces the node into the tree in a different role than the author intended. 

Like I said above, I don't think this is true. We don't know what the author intended—we're in an error scenario. Maybe the message wasn't supposed to start right under the comment? If there's one error in it, how can we be sure there aren't others?

Do you agree that even if they make it into the AST, comments are rather harmless? Do you expect this behavior to cause problems?

**Comment by zbraniecki** [comment]
> Do you agree that even if they make it into the AST, comments are rather harmless? Do you expect this behavior to cause problems?

I don't know. It locks us in a behavior that assumes this, which I think should hold true in the future, but may bite us back.

If you don't share this concern, I think we can close this issue.

**Comment by stasm** [comment]
When I last talked to @zbraniecki  about this, he described his attitude as _not convinced but not blocking_. Let's close this issue.

There are also technical reasons for doing so. It would be hard to implement the change requested here in terms of the [PEG ](https://en.wikipedia.org/wiki/Parsing_expression_grammar)(which the refparser uses). Implementing the behavior dictated by the spec is, OTOH, easy. https://github.com/projectfluent/fluent.js/pull/235 implemented it in the tooling parser in the `fluent-syntax` package.
