### ISSUE TITLE
Remove the Identifier node

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#144]
Right now we have:

```
{
    "type": "Message",
    "id": {
        "type": "Identifier",
        "name": "message-id"
    },
    "value": …
}
```
```
{
    "type": "Term",
    "id": {
        "type": "Identifier",
        "name": "-term-id"
    },
    "value": …
}
```
```
{
    "type": "MessageReference",
    "identifier": {
        "type": "Identifier",
        "name": "message-id"
    },
}
```
```
{
    "type": "TermReference",
    "identifier": {
        "type": "Identifier",
        "name": "-term-id"
    },
}
```
```
{
    "type": "VariableReference",
    "identifier": {
        "type": "Identifier",
        "name": "variable-id"
    },
}
```

Could we simplify the AST by removing the `Identifier` node? It doesn't seem to add much value. Compare:

```
{
    "type": "Message",
    "id": "message-id",
    "value": …
}
```
```
{
    "type": "Term",
    "id": "-term-id",
    "value": …
}
```
```
{
    "type": "MessageReference",
    "identifier": "message-id"
}
```
```
{
    "type": "TermReference",
    "identifier": "-term-id"
}
```
```
{
    "type": "VariableReference",
    "identifier": "$variable-id"
}
```

**Comment by Pike** [comment]
Also `Attribute` and `FooAttributeExpression`.

I'd suggest a __needs_pr__ label for this one ;-)

**Comment by zbraniecki** [comment]
@manishearth - same question as in #142 - is there any reason to store AST nodes with or without denoting sigils?

**Comment by Manishearth** [comment]
If there's a syntactic difference, then yeah, you probably should store them separately. This is kinda the point of an AST vs a lex tree, it separates out things nicely for you to consume.

Going through the grammar it seems like these are all distinct; while there are places where more than one of these fit, they don't overlap completely. They should probably get individual AST nodes.

I don't see why `"type": "Identifier"` is necessary, though. You can also have something like:

```
{
    "type": "MessageReference",
    "identifier": "message-id"
}

{
    "type": "TermReference",
    "identifier": "term-id"
}

{
    "type": "VariableReference",
    "identifier": "variable-id"
}
```

**Comment by stasm** [comment]
Thanks, @Manishearth. I'll go ahead and prepare a PR which removes `"type": "Identifier"`. The question whether to store the `-` as the identifier's name remains open and is being discussed in #142.

**Comment by stasm** [comment]
One thing that we'd lose if we removed the `Identifier` node is the span information. That's probably OK for the `*Reference` expressions since they have their own spans too which are identical or nearly identical to that if the `Identifiers`. However, for `Message` and `Term` this would constitute a problem.

So I don't think we can remove `Identifier` completely. I'd still like to consider simplifying the AST of `MessageReference`, `TermReference` and `VariableReference`.

**Comment by stasm** [comment]
Closing because there aren't many benefits of removing the `Identifier` node and we need spans.
