### ISSUE TITLE
Require indent before placeables

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#170]
A follow-up to #87 based on the discussion in #162.

In #87 (PR #159) we relaxed the indentation requirement for all non-text. This included the placeable's opening brace. For instance:

https://github.com/projectfluent/fluent/blob/a1ed83fea77c9da7456545cac70dd45e76813379/test/fixtures/select_indent.ftl#L15-L18

https://github.com/projectfluent/fluent/blob/a1ed83fea77c9da7456545cac70dd45e76813379/test/fixtures/variants_indent.ftl#L5-L8

The discussion in #162 highlighted a possible issue for preserving some text indent caused by no indentation before placables (https://github.com/projectfluent/fluent/issues/162#issuecomment-415070521). The issue might turn out to be solvable by the design of #162.

Just to be safe, however, should we require indent before placeables in 0.7?

**Comment by Pike** [comment]
I see leading placeables to be in the same bucket as plain white-space lines and blank lines (just `\n`).

They're all leading to absent and/or invisible whitespace, and I expect the fix to be the same for each.

I don't think we need special pre-cautions for placeables.

**Comment by stasm** [comment]
OK, I agree, thanks @Pike. Let's close this then.
