### ISSUE TITLE
Parameterized Terms

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#176]
_a.k.a. The Return of Macros._

In #102 we added `VariantLists`. They are a solution to abusing `SelectExpressions` by not defining the `selector`. Variants of a `VariantList` can be retrieved externally from where the term is referenced with a `VariantExpression`.

The design of `VariantLists` has its own shortcomings which I outlined in https://github.com/projectfluent/fluent/issues/102#issuecomment-385069390 and which required the addition of specialized [code in `abstract.mjs`](
https://github.com/projectfluent/fluent/blob/20a5d258504b3bf8029224bf9c213d465b90af7b/syntax/abstract.mjs#L77-L83) to tightly control where exactly `VariantLists` are allowed.

At the time, we accepted these shortcomings as trade-offs and also because we didn't find other alternatives. I think I may have stumbled across an idea which is worth bringing it up here.

#### Proposal

Rather than treating terms with `VariantLists` for value as dictionaries whose members must be accessed from the outside, what if we encapsulated the member access in a form of a function?

In other words, rather than defining the following term as a `VariantList`:

```properties
# Before, with VariantLists
-fxaccount-brand-name = {
    [lowercase] account Firefox
   *[uppercase] Account Firefox
}

sync-signedout-account-title = Connetti il tuo { -fxaccount-brand-name[lowercase] }
```

We could parameterize it with the `$case` local variable and use a regular `Pattern` as the value:

```properties
# After, with parameterized terms
-fxaccount-brand-name($case) = { $case ->
    [lowercase] account Firefox
   *[uppercase] Account Firefox
}

# Call it similar to a function
sync-signedout-account-title = Connetti il tuo { -fxaccount-brand-name("lowercase") }
```

Using the default variant, or referencing a term which doesn't have any parameters would use the current `TermReference` syntax without any paranthesis:

```properties
# English FTL
sync-signedout-account-title = Connect to your { -fxaccount-brand-name }
```

#### Advantages

- Values of terms can always be `Patterns` again.
- Accessing a specific variant uses the `CallExpression` syntax. No need for the specialized `VariantExpression`.
- Accessing variants would now use the same semantics as `SelectExpressions` in `Patterns` do right now. New features of `SelectExpressions`, like #4, would automatically be available in terms.
- Local variables can be used inside of the term's value, too. The above example doesn't show case this, but you could imagine a different term using a `$number` variable. In the current design, the name of this variable is effectively hardcoded in the term and all messages referencing it must have the variable of this exact name passed into them by the app. This would limit the utility of private terms, which we might introduce in the future.

#### Open questions

1. How should the scoping rules work exactly? Should terms be allowed to access variables passed to messages which reference them, or should all variables be passed to them explicitly?
2. Should attributes use the parameters defined on the term id, or should there be a way to define (possibly different) parameters on the attribute id?
3. Related, when referencing attributes, should the parameters be attached to the term (`{-brand-name("lowercase").gender}`) or to the attribute (`{-brand-name.gender("lowercase")}`)?
4. Could we use named arguments to define default values of parameters?

**Comment by stasm** [comment]
I have a proposal which solves questions: 1, 4, 5, 6, and maybe 7 and 8.

```properties
# @param $case - Letter case to use.
-fxaccount-brand-name = { $case ->
    [lowercase] account Firefox
   *[uppercase] Account Firefox
}

sync-signedout-account-title =
    Connetti il tuo { -fxaccount-brand-name($case: "lowercase") }
```

Let's treat all variables referenced in `Terms` as references to named arguments passed to the term via a `CallExpression`. This means that terms are not allowed to access any variables passed to the message they are referenced from, unless these variables are passed to the term explicitly via the `CallExpression`. This answers question 1.

Terms don't need to define their format parameters in this proposal at all (`-term(arg) = ...`). The parameters are accessed lazily during the resolution of the term from the list of named arguments passed to it. This answers question 4.

When calling a term, both positional and named arguments _can_ be used, but positional are ignored, because, by their anonymous nature, they can't be looked up via variable names. This answers question 5 and 6.

I'm still not entirely sure about question 7 and 8. I can see arguments to both using `-fxaccount-brand-name($case: "lowercase")` and `-fxaccount-brand-name(case: "lowercase")` (without the `$`). I'm erring on the side of consistency from the localizer's POV, which means using `$` everywhere.

**Comment by stasm** [comment]
As far as questions 2 and 3 are concerned, and assuming term attributes are only used to describe grammatical or stylistic properties of the term itself... do we actually need parameterization there?

```properties
-brand-name =
    { $case ->
       *[nominative] Firefox
        [accusative] Firefoxa
    }
    .gender = masculine

has-updated =
    { -brand-name.gender ->
        [masculine] { -brand-name($case: "nominative") } został zaktualizowany.
        [feminine] { -brand-name($case: "nominative") } została zaktualizowana.
       *[other] Program { -brand-name($case: "nominative") } został zaktualizowany.
    }
```

**Comment by Pike** [comment]
[Vowel harmony](https://en.wikipedia.org/wiki/Vowel_harmony) could be a use-case (didn't read the article in full) where you'd like to denote to the calling site that the term's dominating vowels depend on case or plurality?

**Comment by stasm** [comment]
Interesting, thanks for the link.

I'd also like to point out that it's not possible to achieve this with the current design of `VariantLists`, either: `-term.attr[name]` is not valid syntax.

**Comment by stasm** [comment]
As I was researching this issue, I realized the current design of `VariantLists` has more limitations than I initially considered. I filed #187 and #188. Macros could be a way to fix them, if we removed `VariantLists` along the way. If not, we should look into fixing them in some other way.

**Comment by stasm** [comment]
I'd like to move forward on this proposal. I opened #205 with a WIP implementation allowing the `-term(arg: "value")` syntax. I'm leaving accessing variants of attributes out of scope for now; we'll add them in #189. I also filed #204 to remove `VariantLists`.
