### ISSUE TITLE
Number ranges

### ISSUE THREAD

**Issue by mmstick** [projectfluent/fluent#177]
Was wondering if there was any thought towards this kind of possibility, without having to create a function for it.

```
thing = $count {
    [0] Not a single thing
    [1] A single thing
    [2..10] A few things
    [11..100] Many things
   *[other] Too many things
}
```

**Comment by stasm** [comment]
Hey, thanks for filing the issue! We considered ranges at some point, but we chose to focus on the plurals use-case. The reality is quite complex and hard to model with a series of ranges alone. Many languages use [complex arithmetic to pick the correct plural category](http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html). Do you see other use-cases which would benefit from number ranges?

**Comment by stasm** [comment]
I'm going to close this issue. The use-cases that I'm aware of are well supported by the plural rules logic, or by creating a function builtin.

As an example, @zbraniecki mentioned it would be useful to run select logic based on the size of the screen. While it's tempting to consider number ranges for this use-case (`[768..1024]`), I think a better solution is for developers to create a special-purpose builtin, `SCREEN_SIZE()` which returns a well-known list of keywords (`small`, `medium`, `large`, or `mobile`, `tablet`, `desktop` etc.). This has the advantage of being easily testable from the developer's POV, and less error-prone from the localizers' POV.

Please reopen this issue if there are other use-cases which cannot be supported in a similar fashion. Thanks!
