### ISSUE TITLE
Allow accessing nested VariantLists

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#187]
There is currently no way to access variants nested in other variants:

```properties
-brand-name = {
    *[singular] {
        *[nominative] Thing
        [genitive] Thing's
    }
    [plural] {
        *[nominative] Things
        [genitive] Things'
    }
}
```

```properties
# Nested VariantExpressions (currently syntax errors)
A = {-brand-name[singular][genitive]}
B = {-brand-name[singular, genitive]}
```

If #176 is accepted and if parameterized terms replace variant lists, we might not need this at all. Otherwise, I would suggest to use the same syntax as will be used for list selectors (#4). My comment in https://github.com/projectfluent/fluent/issues/4#issuecomment-431324345 has the rationale for my preference for option B.

**Comment by stasm** [comment]
For both A and B we should find an answer to the question no. 6 from https://github.com/projectfluent/fluent/issues/176#issuecomment-431331767. Should be it possible to invoke the default value of an upper level and pass a specific key to the nested `VariantList`? In pseudocode:

```properties
# Either a new Fluent symbol NONE,
# or just leverage the fact that no variant has key == NONE.
X = {-brand-name[NONE, genitive]}
# Empty placeable could mean "null"
X = {-brand-name[{}, genitive]}
# Implicit "null"
X = {-brand-name[, genitive]}
```

I don't like any of these solutions. I think we should encourage explicit syntax, especially in areas which are already quite complex. Terms with variant lists definitely qualify as such in my book. I'm OK with answering _No_ to the original question, and requiring all keys to be always present:

```properties
B = {-brand-name[singular, genitive]}
```

**Comment by stasm** [comment]
Parameterized terms (#176) supersede variant lists, making this issue obsolete. I filed #204 to remove variant lists from the syntax.

**Comment by mariusrak** [comment]
Hi, can you please explain how can I use parametrized terms to achieve what variant lists would allow? Thanks.

**Comment by artlung** [comment]
@mariusrak I suspect this is not a great place to ask a question like that. But I suspect looking at https://projectfluent.org/fluent/guide/selectors.html will get you started at how to create `ftl` with variants. Also if I had a question I might feel inclined to ask on StackOverflow with a `project-fluent` tag. https://stackoverflow.com/questions/tagged/project-fluent
