### ISSUE TITLE
ICU underneath?

### ISSUE THREAD

**Issue by tzutalin** [projectfluent/fluent#216]
Hi, 
Sorry, I didn't dive deeper beforehand. I have a quick question about the implementation of Fluent. How does Fluent do formatting? Do it use ICU formatting underneath, Fluent do the formatting on itself, or just use Intl formatting in JS? From my understanding, Intl is employing ICU.

**Comment by stasm** [comment]
Hi @tzutalin! The answer depends on the implementation. In JavaScript, I think most engines use ICU for formatting.

At its core, Fluent is a specification of a syntax used to store translations (the Fluent grammar) and the logic to format them such that they are ready to be used in the UI (the Fluent runtime). Right now we've mostly focused on the grammar part while the runtime part still needs more work to be well-specified. Once we get there, the specification will likely dictate that implementations format numbers and dates according to the rules of the given language (e.g. by using existing i18n solutions, like ICU).

Right now, we're focusing our efforts on three implementations listed below. I also know of a few more (C#, Elm) but I don't know what i18n solution they use.

- JavaScript: `fluent.js` [uses](https://github.com/projectfluent/fluent.js/blob/a6bab32256e0148aa3256ba949cde1b583be0fe3/fluent/src/types.js#L62) the [`Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) specified by ECMA 402. I think that most browsers use ICU to implement it, although I'm not sure about Edge. @zbraniecki, can you confirm this, please?

- Python: There's an [open PR to `python-fluent`](https://github.com/projectfluent/python-fluent/pull/67) to add the runtime logic and it uses the [Babel package](http://babel.pocoo.org/en/latest/) to format numbers and dates. AFAICT, Babel doesn't use ICU under the hood.

- Rust: `fluent-rs` doesn't currently format dates nor numbers at all. According to [this issue](https://github.com/projectfluent/fluent-rs/issues/19), there weren't any i18n solutions available in the Rust ecosystem as of last year. I don't know if the situation has changed. We'll look into it early next year when `fluent-rs` hopefully becomes a priority for us.

Does this answer your question?

**Comment by tzutalin** [comment]
Thanks for your explanation. You did answer my question and I also check the resource code. fluent.js used `Intl API(ICU impl)` to do formatting.  Have you planned to work on Java side? The tricky part for Java is to parse FTL's grammar and message and convert to ICU message.
