### ISSUE TITLE
Rename Terms to Macros

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#231]
Terms and term attributes can be parameterized since Syntax 0.8. Parameterization is a long and hard-too-pronounce word. Would _macros_ be a better name for what terms are?

**Comment by stasm** [comment]
Let's give ourselves this week to consider different alternatives. If nothing's significantly better than _terms_ (which I agree describe the concept well), I'll close this issue. Thanks for sharing your thoughts!

**Comment by zbraniecki** [comment]
I agree with Pike.

**Comment by stasm** [comment]
It looks like there aren't any good enough reasons to rename terms.

Wrt. parameterization, maybe _terms with variants_ and _term attributes with variants_ would be an easier to pronounce alternative, suitable for tutorials and guides? In spec, I would probably prefer to continue to use _parameterized_.

**Comment by stasm** [comment]
Closing as per my last comment.
