### ISSUE TITLE
Any plans to write a po to flt converter?

### ISSUE THREAD

**Issue by adjenks** [projectfluent/fluent#233]
Server side translations are traditionally done using po(t) files and searched using "gettext()" in most languages.

Does the team plan on building tools to convert from po to flt? I think this would speed up adoption greatly.

**Comment by Pike** [comment]
We have a converter to Fluent files, in https://hg.mozilla.org/l10n/fluent-migration/. We haven't tried to convert from gettext files yet.

The documentation for converting to Fluent from the more obscure Mozilla-internal formats is on https://firefox-source-docs.mozilla.org/intl/l10n/l10n/fluent_migrations.html. The library that reads the legacy translations has gettext support, but we don't use that in any practical project yet, so there might be dragons.

If you want to give it a try, I'd be curious to learn how that pans out.

**Comment by adjenks** [comment]
Okay, thank you. I'll let you know if I try.

**Comment by snailuj** [comment]
Note for anyone else. Was keen to view the documentation mentioned by @Pike, but at time of writing it was 404ing. I found what I was after at https://firefox-source-docs.mozilla.org/l10n/migrations/index.html
