### ISSUE TITLE
Store number values as strings of digits

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#239]
> I like to think about AST as a structured, semantic view of the source string.
>
> From that perspective, what if we stored a number as a slice `[start;end]` and parsed it in the resolver instead?
>
> My concern here is that storing numbers and parsing them differs between different programming languages Fluent may work in. Number is a low level primitive, but it still can differ in how it stores fractions, unsigned vs signed etc. By keeping AST free of that logic, we ensure that the AST is portable between the implementations irrelevant of how JS, Python or Rust treat numerical values.
>
> Not a blocker, just a suggestion.

_Originally posted by @zbraniecki in https://github.com/projectfluent/fluent.js/pull/342_

**Comment by stasm** [comment]
I like this suggestion, but I also don't mind the current design of the AST. I wonder if it would make sense to provide both representations, similar to how we do it for raw and cooked `StringLiterals`. One representation is a string of digits and the other one: a float value.

Here's how JSON approaches this problem (https://tools.ietf.org/html/rfc7159#section-6):

> This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.

> Note that when such software is used, numbers that are integers and
   are in the range `[-(2**53)+1, (2**53)-1]` are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

It's worth mentioning that in the context of localization and Fluent Syntax, `NumberLiterals` are rarely used in general. They're the most useful as named arguments values (where precision doesn't matter, but the numerical value does) and as variant keys. For the latter, we're looking at exact matching intergers and simple floats like `1.0`. IEEE 754 should be enough.

@Pike Do you have an opinion on this?

**Comment by stasm** [comment]
I opened #241 with an example implementation described in my previous comment.

**Comment by stasm** [comment]
A quick survey of ASTs produced at https://astexplorer.net/ suggests that the `{value: NumberType, raw: StringType}` approach is a common solution to storing number literals in many languages.

**Comment by zbraniecki** [comment]
I started porting fluent-rs to 0.9 and updated the fixtures there. While working on that I encountered the kind of issue I was worried about:

Fluent's `1.03` number will be stored as `NumberLiteral { raw: "1.03", value: 1.03, precision: 2 }`.
Fluent's `1.00` number will be stored as `NumberLiteral { raw: "1.00", value: 1.0, precision: 2 }` *or* `NumberLiteral { raw: "1.00", value: 1, precision: 2 }`.

It just so happens, that JS implementation collapses `1.0` when stringifying numbers to JSON into `1`, but JSON can perfectly well store `1.0` as well, and it just so happens that Rust distinguishes between float and integer, so since there's `.` in the number, it treats it as float and stores `1.0`.

As I said, it's a minor issue of course, and can be worked around with some hackery (check that all fractionals are `0` and then cut off on `.` and treat the number as integer), but that seems like an implementation detail of the JS leaking onto our AST.

Could we consider storing only `raw` on the `NumberLiteral` to maintain the AST portable and implementation independent?

**Comment by Pike** [comment]
fwiw, the json implementation in python does the same thing, "1" is different to "1.0", but then again, `1 == 1.0` is true in python ;-)

**Comment by stasm** [comment]
> Could we consider storing only `raw` on the `NumberLiteral` to maintain the AST portable and implementation independent?

I think that would effectively undo #235. Do we want to do that? Alternatively, we could store `raw` _and_ `precision`, so that it doesn't have to be computed by the resolver.

**Comment by stasm** [comment]
> It just so happens, that JS implementation collapses `1.0` when stringifying numbers to JSON into `1`, but JSON can perfectly well store `1.0` as well, and it just so happens that Rust distinguishes between float and integer, so since there's `.` in the number, it treats it as float and stores `1.0`.

I wonder if that's actually OK. When you read a JSON representation of an AST into your program in Rust, you probably have to tell it precisely to parse `NumberLiteral.value` as an `f64`. So two `NumberLiterals` should compare equal. Then again, can you actually compare floats in Rust reliably?

When you do read JSON in in Python, it parses `1.0` as a `float` and `1` as an `int`, but the comparison also works fine, as @Pike observed in his comment above.

Lastly, JavaScript treats `1.0` and `1` as the same number; the equality is ensured, too.

I didn't look into other languages, but I suppose they implement one of the above three models, too, thus ensuring correct equality checks. However, storing a string representation of the number might be a safer thing to do regardless.

**Comment by stasm** [comment]
OK, after talking about this more in person with @Pike and @zbraniecki, it looks like the best course of action is to revert #235 and go back to storing just the string representation of the number literal. Thank you for the input!
