### ISSUE TITLE
Parametrized Terms allow for empty call-args and positional parameters

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent#240]
Right now, the prmtized terms as added in #221 allow for the following:

```properties
zero = {-term}
one  =  {-term()}
two = {-term('joe')}
```

All of these are functionally equivalent, i.e., they do the very same thing.

From a POV of wanting clear expectations on who to write something in Fluent, only `zero` makes sens. And then we'd throw parse errors in `abstract.mjs`.

From a POV of being lenient what you accept, we'd allow all three. We could add a warning for anything non-`zero` in tools, maybe?

From a POV of editor support, maybe `one` is OK as an intermediate editing step to an actual prmtized term, but `two` wouldn't.

I struggle to clearly have a hat on.

**Comment by flodolo** [comment]
I might be completely missing the point, but the only one that makes sense to me is zero, because otherwise it would be `{ -term(foo: "bar") }`.

**Comment by stasm** [comment]
You're correct. `one` and `two` are not very useful, but they currently are valid syntax. It's just that they don't do much in the runtime. This is similar to how select expressions with hardcoded selectors (`"abc" -> ...`) are valid syntax too, and yet adding variants to them is pointless.

The question here is whether the `(...)` syntax in `-term(...)` should have the same or different semantics than the same syntax in `FUNC(...)`. By semantics, I mean the specification of the allowed arguments.

**Comment by Pike** [comment]
We decided to be lenient about this in the syntax, but that it would be good to have warnings about `one` and `two` in compare-locales. [Bug 1529589](https://bugzilla.mozilla.org/show_bug.cgi?id=1529589) filed.
