### ISSUE TITLE
Clicking next arrow on bottom of functions page of doc goes to top of page

### ISSUE THREAD

**Issue by missmatsuko** [projectfluent/fluent#255]
When you click the next arrow link at the bottom of [the functions page in the guide](https://projectfluent.org/fluent/guide/functions.html#using-functions), it links to the first heading under functions, "Using functions", which is near the top of the page.

Since I already scrolled to the bottom of the page, I would've expected this link to go to the next section, "Learn more"

I think it's because SUMMARY.md has entries which are hashes on the same page. I'm not sure if GitBooks' table of contents recognizes that.

**Comment by stasm** [comment]
Thanks for reporting this. I fixed it by removing the subsections from the tables of contents. I think linking the whole `Functions` chapter is enough for now.

I also filed #256 to look into replace Gitbook with another tool. Gitbook isn't maintained anymore, so it might be a good idea to migrate off of it.
