### ISSUE TITLE
Migrate away from gitbook

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#256]
The `gitbook` CLI tool [has been deprecated](https://github.com/GitbookIO/gitbook/commit/6c6ef7f4af32a2977e44dd23d3feb6ebf28970f4). Let's find an alternative, e.g. [`mdbook`](https://rust-lang-nursery.github.io/mdBook/).

**Comment by flodolo** [comment]
Just stumbled upon this. We moved away from the the l10n docs, and it was pretty straightforward.

Hard to point to a single commit, but you can get an idea from
https://github.com/mozilla-l10n/documentation/blob/master/.travis.yml

One of the things we had to fix was absolute links
https://github.com/mozilla-l10n/documentation/commit/cd91558479462b4f35ce77baaacbf90e39492425

**Comment by heyakyra** [comment]
Opened #362 but not really able to test since the deployment seems to be handled elsewhere

Also created https://github.com/heyakyra/fluent-companies if pepole know of organizations using Fluent
