### ISSUE TITLE
Alternates?

### ISSUE THREAD

**Issue by passcod** [projectfluent/fluent#262]
In some cases, for me around small games (to add whimsy) and human-interacting bots (to break monotony and appear less, well, boring), it's desired to have multiple alternates for a single message. Alternate selection can be anything from purely random to more complex behaviours... I wouldn't expect Fluent to do that, but I would like a way for Fluent to support alternates.

As a trivial example, a whimsical bot says goodbye when exiting a channel:

```properties
goodbye-alt-1 = It’s been a privilege
goodbye-alt-2 = See you later
goodbye-alt-3 = I’ll see you on the other side
```

From this, in the code I can query a resource bundle for this format give a prefix ("list all alternates for `goodbye`") and then pick one at random. That works, but syntactic support would work better: both for authors, as currently this is a protocol "on top", and is easily broken inadvertently; and for implementers, where re-parsing the alternate groupings is not necessary and the alternate mechanism can be relied on robustly.

Another longer example, with optional interpolation:

```properties
motivate-alt-1 = Wake up. Kick ass. Repeat.
motivate-alt-2 = You’re gonna make it happen!
motivate-alt-3 = Your words are magic. Recharge! Then cast again.
motivate-alt-4 = Take a chance, { $name }. It may be bad, but it’s the only way you can do anything really good.
motivate-alt-5 = Always be a poet, even in { $medium }.
```

And an error scenario with a selector and two special alternates: one default, and one context-dependent (permissions related):

```properties
error-too-far-alt-default = { $hourCount ->
	[one] an hour
	*[other] { $hourCount } hours
	} is too far into the future, sorry.
error-too-far-alt-can-escalate = Try with more bang!
error-too-far-alt-1 = Nope.
error-too-far-alt-2 = No can do
error-too-far-alt-3 = You’re asking the imp… er. Well, the improbable, at least.
error-too-far-alt-4 = meenie minie moe… for you this will be no!
```

**Comment by Pike** [comment]
If you added a carefully crafted `RANDOM` global to your setup, you could do

```
error-too-far = {RANDOM("one", "two", "three") ->
  *[one] Nope.
   [two] No can do
   [three] You're asking the imp… er. Well, the improbable, at least.
}
```

Are there aspects that you couldn't implement like this?

**Comment by passcod** [comment]
That makes Fluent choose, rather than application code, right? So I'll only ever have one or a limited amount of logic, rather than specialising the choosing logic per call site.

I realise the last example doesn't really make that explicit. Consider two different application contexts for the one message:

1. is a first error, where whimsy is okay. Calling code decides whether `can-escalate` can be included based on permissions, then does a weighted random choose biased 20% towards the default.
2. is a repeat error, where whimsy is at risk of frustrating the user. The choosing code almost always goes for the default, with a diminishing probability of whimsy starting at 5%.

This is fairly simple logic still, with only two dimensions. Some call sites can have very complex logic, both on the pool selection, the meaning of a default, and the random distribution. That logic belongs in the application!

----

This may feel like a niche case that doesn't fit within the fluent vision and would only encumber the syntax, and that's okay. I'm happy enough with the present situation, but wanted to show this usecase to at least let it be known :)

**Comment by Pike** [comment]
Could you explain a bit more what you'd expect in terms of APIs?

**Comment by passcod** [comment]
Apologies for forgetting a bit about this issue; got busy. I recently implemented this pattern in public code, with Fluent's low level Rust interfaces. So, as a sample... https://github.com/storily/garrire/blob/main/src/locale.rs

The "glitchiness" factor in this implementation is unique to the application and can be ignored (along with the added complexity it brings) for the purposes of this issue.

**Comment by zbraniecki** [comment]
So, you can craft the RANDOM function to be whatever you want and feed it to fluent from your application. That makes your app choose.

**Comment by passcod** [comment]
Sure, ok
