### ISSUE TITLE
Change the comment sigil

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#28]
If we go for the _hashtags_ in #7, we'll need to find another sigil for comments.  @Pike suggested that a simple tool which helps visualize different options might be useful. I consequently created https://people-mozilla.org/~stas/sigils/.

**Comment by stasm** [comment]
I like `--` for comments: https://people-mozilla.org/~stas/sigils/?comment=--&trait=%23

**Comment by Pike** [comment]
The # for grammar is easier on me than the + was.

That said, I find -- a bit hard on the eye for multiline comments. Playing around with [//](https://people-mozilla.org/%7Estas/sigils/?attr=.&com=%2F%2F&def=%2A&example=genders&ext=%24&tag=%23&txt=) felt easier to read to me.

**Comment by flodolo** [comment]
I don't like `--`, and I've been bitten so many times by auto-correct before, trying to be smart and changing my -- to – in IRC conversations.

`//` seems like a natural alternative.

**Comment by stasm** [comment]
OK, let's go with `//`.

**Comment by zbraniecki** [comment]
IIRC the plan was to run a mini UX survey among 4-5 users. Did the plan changed?

**Comment by stasm** [comment]
No, the plan didn't change. Over the course of last week I talked to Flod, Théo, Stef and Piotr.  Flod responded above, Stef liked `#` for tags and `//` for comments but in general had reservations regarding our use of brackets and said he'd prefer more sigils instead. Piotr didn't have an opinion and in general felt that FTL was complicated. Théo said he needed more time to familiarize himself with core concepts of FTL before he could answer.

My take-away is that conservative changes that can be reasonably justified are OK. Which is why I'd like to go ahead with `//` as the sigil for comments and with `#` for tags in #7.
