### ISSUE TITLE
SelectExpression definition wrong

### ISSUE THREAD

**Issue by alerque** [projectfluent/fluent#298]
I realise the EBNF is not actually the spec and is autogenerated by the reference parser, but however you cut the mustard [this line](https://github.com/projectfluent/fluent/blob/f52c3aad36aea8f28c6f106990511b62a89d495b/spec/fluent.ebnf#L78) is wrong:

```ebnf
SelectExpression    ::= InlineExpression blank? "->" blank_inline? variant_list
```

In actuality this cannot be _any_ of the `InlineExpression` types. It cannot be `MessageReference`, `TermReference`.

**Comment by Pike** [comment]
Please see https://github.com/projectfluent/fluent/blob/master/spec/valid.md and https://github.com/projectfluent/fluent/blob/f52c3aad36aea8f28c6f106990511b62a89d495b/syntax/abstract.js#L53-L67.

It is an intentional decision to keep the EBNF simple and to describe only well-formed syntax, not all aspects of valid syntax.

**Comment by alerque** [comment]
I don't understand why this is considered "well formed" when the syntax contains something the grammar doesn't allow. In this case the reference fixtures want to make something that breaks this rule into a Junk, but the grammar mandating that it be a parsed as a Junk because it has syntax features not allowed there is different than throwing an error about an invalid value.

**Comment by alerque** [comment]
Also besides that confusion, there seems to be another inconsistency here. The `abstract.js` code you pointed out explicitly **allows** `FTL.TermReference` nodes as selectors, yet the test fixtures explicitly **reject** this:

https://github.com/projectfluent/fluent/blob/f52c3aad36aea8f28c6f106990511b62a89d495b/test/fixtures/reference_expressions.ftl#L22-L25

**Comment by alerque** [comment]
Regarding Terms, it appears the difference is that `Term`+`Attribute` but not bare `Term`s is allowed, so `-term.attr` but not `-term`. The artificial split between "well formed" and "valid" is making this harder than it should be to implement because the actual *spec* behavior is not defined in any one place, it's spread out over at 3 or 4 places that tweak each other.
