### ISSUE TITLE
Playground language selection not working

### ISSUE THREAD

**Issue by afd998** [projectfluent/fluent#315]
The output seams to hot reload when I change the direction of the text or the text itself but when I change the language the output doesn't change? is this a bug?

**Comment by Pike** [comment]
It does for me. I tried switching to Russian, and it showed a singular message for 21, and to Arabic, and it showed Arabic numerals.

The playground doesn't actually try to do any translation, it just changes Intl data and settings based on it.

I'll close this issue, feel free to reopen if you have further details.
