### ISSUE TITLE
Documentation on projectfluent.org is not updated

### ISSUE THREAD

**Issue by hongquan** [projectfluent/fluent#347]
For example, here is a code snippet in https://projectfluent.org/fluent/guide/functions.html:

```js
ctx.format('today', {
  day: Intl.MessageDateTimeArgument(new Date(), {
    weekday: 'long'
  })
})
```

This one doesn't work. The one in documentation [source](https://github.com/projectfluent/fluent/blob/master/guide/functions.md) (md file) works:

```js
ctx.format('today', {
  day: new FluentDateTime(new Date(), {
    weekday: 'long'
  })
})
```

**Comment by eemeli** [comment]
Thank you for pointing this out! The website should now have updated contents.
