### ISSUE TITLE
Implementers feedback on EBNF

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#36]
I started looking into aligning the parser with the full EBNF and encountered a few gotchas:

First of all, the fact that `inline-space` and `line-break` are not single characters but ranges with `+` seems to be unnecessary. You still seem to be using them (and their aliases `_` and `NL`) with quantifiers that seems as if you wanted to indicate if there is a single white space allowed, or multiple and if it is a `+` or `*` or `?` quantifier.

Capturing multiple newlines within a single `line-break` just to put a `?` for it in the caller, seems to be unnecessary and confusing.

On to details:
* body
** As mentioned above, the `_*` is confusing with `_ = []+`
** It doesn't seem like it allows for whitespaces (except of NL) to be between entries. Is that intentional? Should an empty line with spaces between entries be a parser error?
* comment
** there doesn't seem to be anything that captures `NL` which makes it not work with multiline comments
* number
** doesn't seem to support negative numbers `-100.23`

That's it for now. Will wait for test infra to start implementing it and writing tests for the edge cases at the same time, so I expect I'll discover more.

**Comment by stasm** [comment]
Thanks for filing this, it's very helpful!

> First of all, the fact that inline-space and line-break are not single characters but ranges with + seems to be unnecessary. You still seem to be using them (and their aliases _ and NL) with quantifiers that seems as if you wanted to indicate if there is a single white space allowed, or multiple and if it is a + or * or ? quantifier.

This was modeled after W3C: https://www.w3.org/TR/REC-xml/#NT-S. They use the `+` as the default and then use the `?` quantifier if needed.

>  It doesn't seem like it allows for whitespaces (except of NL) to be between entries. Is that intentional? Should an empty line with spaces between entries be a parser error?

@Pike, I feel like we talked about something very similar. Did I forget to make a change in how `body` is defined? [Right now](https://github.com/projectfluent/fluent/blob/03f387ccab170b4b98756cc16d1d705f8ce4ad53/spec/fluent.ebnf) it's `(entry NL)*`.

> comment - there doesn't seem to be anything that captures NL which makes it not work with multiline comments

Will this be enough?

```diff
-comment ::= ('//' (char - NL)* )+
+comment ::= ('//' (char - NL)* NL)+
```
> number - doesn't seem to support negative numbers -100.23

Thanks again. I filed https://github.com/projectfluent/fluent/pull/37.

**Comment by stasm** [comment]
I filed #60 and #61 to fix the other two issues reported here.

**Comment by stasm** [comment]
All the issues have been addressed. Thanks for the feedback!
