### ISSUE TITLE
syntax guide seems to be down

### ISSUE THREAD

**Issue by fee1-dead** [projectfluent/fluent#366]
When I go to https://projectfluent.org/fluent/guide/, it says page not found.

**Comment by eemeli** [comment]
I've rolled back the recent updates to the `gh-pages` branch while we sort this out.

CC @flodolo, its previous HEAD was at bf77968, which appears to have content in the root rather than the `guide/` directory.

**Comment by flodolo** [comment]
I checked the address in the [workflow](https://github.com/projectfluent/fluent/actions/runs/7625922770) and it was working, didn't realize it was different (it was loading https://projectfluent.org/fluent/)
