### ISSUE TITLE
Add ability to present a message as a simple string

### ISSUE THREAD

**Issue by mathjazz** [projectfluent/fluent#39]
In parts of UI (e.g. a list of messages), translation tools cannot present the entire FTL message due to space limitations. For pluralized messages, they usually only show the singular form. Similarly, they will only show the default variant for messages with multiple variants.

Fluent should provide a simplified presentation of each message in a string form. Either in AST directly or through a method taking AST as an argument. This will allow tool developers to quickly get the message presentation as a simple string, instead of writing their own logic, which will lead to inconsistencies among tools.

**Comment by Pike** [comment]
There are two use-cases here, I think.

One is the list-display, which I expect to show up in many form-based tools.

The other is TM interactions, for which we probably want some sort of canonical representation of both en-US and l10n to send over to TM.

**Comment by mathjazz** [comment]
I see value in "TM" as a separate function that takes both, original and translated message as an input and outputs 1 to N original-translation pairs to be used as TM entries.

**Comment by stasm** [comment]
In https://github.com/projectfluent/fluent.js/pull/9/commits/73fbab807542cbb9b8004ad40816b57cd2c93285 I added `MessageContext.formatToParts` which can be used to replace unresolved placeables with the names of arguments.

I put together a demo to illustrate how `formatToParts` could help: http://jsbin.com/pahoqas/edit?js,output

**Comment by zbraniecki** [comment]
@mathjazz - can we close this now? Is that enough for you?
