### ISSUE TITLE
identifier definition inconsistency ?

### ISSUE THREAD

**Issue by ctjhoa** [projectfluent/fluent#44]
Hi,

I'm not familiar with language grammar but I find something weird with the `identifier` definition.

According to the railroad diagrams and ebnf file here is the definition:
![2017-05-08-154141_457x584_scrot](https://cloud.githubusercontent.com/assets/1716173/25806821/dbc9b4fc-3404-11e7-90df-9f84c9a919d3.png)
This suppose to match strings like:

```
-abcde = abcde
a?cde = abcde
?bcde = abcde
```

Unfortunately, testing these cases in the fluent playground leads to a parser error.
http://projectfluent.io/play/?gist=6c28357ea7079cfc83f65789e551b67b

Can you confirm the good implementation? and do you know where I can find the source of the parser used in the playground?

Thanks

**Comment by stasm** [comment]
Thanks for filing the issue, @ctjhoa! The Playground [uses][1] the [`fluent-syntax`][2] package.

[1]: https://github.com/projectfluent/play/blob/a2754df37425b0511517c9c1c5b83e5277537171/package.json#L13
[2]: https://github.com/projectfluent/fluent.js/tree/master/fluent-syntax

It's still an early version of the parser and it might be lacking a bit.  There's a new version available and I'll update soon. I don't think we made any changes to how Identifiers are parsed, though, so I doubt that the error will go away with this update.

I'll be happy to review a fix for this issue :)

**Comment by zbraniecki** [comment]
I reported #49 about `?`.

**Comment by zbraniecki** [comment]
I reported #50 about `-`.

**Comment by stasm** [comment]
#49 and #50 have both been closed. I also file https://github.com/projectfluent/fluent.js/issues/84 to implement the change in fluent.js.
