### ISSUE TITLE
Cannot find definition of FTL acronym

### ISSUE THREAD

**Issue by anaran** [projectfluent/fluent#45]
It seems to at least be hard to find, in case it is documented anywhere.

How about putting it in the README.md, where it is likely first encountered.

**Comment by stasm** [comment]
Hi, @anaran, thanks for the report! The acronym is expaneded in `spec/README` but I agree it's not very discoverable.  I added a `README` in the root of the repo in https://github.com/projectfluent/fluent/commit/a9fb740ecbf9326a484b812800f62a338a43f7da.
