### ISSUE TITLE
Remove `?` from allowed characters in ID, Symbol, Keyword and NamedArgument

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#49]
The current spec allows for `?` character to be present in ID, Keyword, Symbol and NamedArgument.

I believe that this is more confusing then helping anyone and we should not do this.

Examples of things that are allowed by the spec:

```

[[ ? ]]
? = Value

? = { ? }

? = { ?[?] }

? = { ? =>
        [?] Variant
    }

? = { ?() }

? = { ?(?=0) }
```

I recognize that characters like `-` and `_` can be called out the same way, but I do see a particular value of being able to use them in ID and function name at least (although I'd prefer to limit that to non-first character)
The `?` character is the only one that I see confusing and unnecessary in all identifiers and keywords.

Since the parsers were never updated to handle that, I also believe that it would be an easy change to make.

@Pike , @stasm , @flodolo , @mathjazz - opinions?

**Comment by Pike** [comment]
sgtm

**Comment by mathjazz** [comment]
I'm ok, too.

**Comment by stasm** [comment]
I think we should follow what we did in #50 and forbid `?` at the beginning of identiifers, and allow it elsewhere. I feel strongly about the benefit of allowing identifiers like `really-close-file?` as opposed to `really-close-file`. Same with function names: `VOWEL?()` reads better to me than `IS_VOWEL()`.

**Comment by zbraniecki** [comment]
Just for the record: I feel the opposite to @stasm - that `?` as a sigil is unnecessary, unfamiliar (not present in CSS, JS, PHP etc.) and on top of things removes a sigil from the scope of potential semantic sigils in the future.
Due to the nature of the sigil, it's likely only going to be present at the end of the variable/id/arg which increases the confusion factor since it can be both.

I also believe that for dont-make-me-think reasons, `IS_VOVEL` is better than `VOVEL?()` and `really-close-file = Really close file?` is better than `really-close-file? = Really close file?`.

**Comment by stasm** [comment]
In #51 we made it illegal for an `Identifier` to start with `-`, `_` or `?`. This answers most of the concerns outlined in the OP.  I would still like `?` to be a valid character at other positions in identifiers. Most languages disallow it because they use `?` for ternary `if`s or wildcards. We don't have these limitations and can thus follow in the footsteps of Clojure or Ruby.
