### ISSUE TITLE
Forbid `-` at the begining of ID/Symbol

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#50]
The parsers currently allow "-" in the middle of ID and Symbol, but not at the beginning.

So, ID such as `-foo` is not allowed, while `foo-faa` is. I'd like to propose adding this limitation to the syntax instead of removing it from the parser.

**Comment by Pike** [comment]
Restricting the first character to letter-class matches my expectation. Not sure I feel strongly about that expectation, though.

**Comment by stasm** [comment]
This sounds good to me, let's change it in the spec.

**Comment by stasm** [comment]
Note that this change should really just apply to Identifiers, and not Symbols, which are designed to be rather free-form. 

While we're at it, should we also forbid `_` at the beginning of identifiers?
