### ISSUE TITLE
Specifying accesskey's

### ISSUE THREAD

**Issue by oeekker** [projectfluent/fluent#56]
It would be great if you can specify which letter to use for the accesskey, instead of only specifying the accesskey. Otherwise you might end up with an accesskey in the middle of a word, while an accesskey at the start of a word is more visible. Also some words are better suited to use as accesskey, e.g. verbs.

Another use case may be accesskeys combined with variables:

  move-again
    .label = { Move to "{ $directory }" again }
    .accesskey = a

Here you might end up with an accesskey in the directory placeholder, and it would be better to have it on a fixed place.

See also https://bugzil.la/1145116 for a similar bug on l10n.

**Comment by Pike** [comment]
This isn't something that needs to be supported in the platform itself, we can't fix it on the fluent side of the stack. We just don't have access to it.

Depending on how platforms allow that to be done, we'll need to find ways to expose that to localizers in fluent, and hook that up through the bindings.

At least in the XUL case, we're not going to invest in a fix for that anymore. We'll remove XUL before that'd happen.

Closing this issue.
