### ISSUE TITLE
Unify the naming scheme

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#57]
We now fairly intuitively jump between naming Fluent "library" and "framework" and "family of libraries". I recently noticed that gettext uses the term "localization system".

It's particularly confusing because on the wiki [1] we list "localization framework" as a non-goal, and then on fluent.js README.md [2] we state that it is a "localization framework".

I have to say I like how it sounds for us as well. Library or libraries are part of implementation of Fluent, and a framework is for me a wider term that takes a library and tools around it, but Fluent is even wider than that.

It introduces a new paradigm and methodology that guides holistically how localization should be done and informs any bindings, libraries, frameworks, tools and workflows based on its paradigms and features.

[1] https://github.com/projectfluent/fluent/wiki 
[2] https://github.com/projectfluent/fluent.js

**Comment by stasm** [comment]
> I have to say I like how it sounds for us as well.

Did you mean to write _I don't like_ here?

Are you suggesting we use _system_? I'm fine with that.

**Comment by zbraniecki** [comment]
I mean that I like the name "system" for what Fluent is. I like it more than "library", "framework" and "family of libraries".

**Comment by stasm** [comment]
I think _system_ is broad enough to capture what we're doing pretty well. It's also less pretentious than _paradigm_.

**Comment by stasm** [comment]
As a first step, @zbraniecki landed https://github.com/projectfluent/fluent/commit/27abf745d09e12b5489259576394d08ecf96475d. We'll need to change READMEs of other Fluent projects.

**Comment by gueroJeff** [comment]
What is the rationale for 'system'?

**Comment by stasm** [comment]
The OP explains why other words, like _framework_ or _library_ are not good fits for the large spectrum of things the Fluent is. I don't _love_ the word _system_ but I agree with @zbraniecki that it describes Fluent better than the alternatives.

Let's stick to using _system_.
