### ISSUE TITLE
Change tag sigil

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#59]
#### Goal
Allow to use `#` for comments in #58.

#### Description
We chose `#` for tags in #7 and actually had to change the comment sigil from `#` to `//` in #28. If the Comments Levels (#58) gets enough support I'd like to reclaim `#` for comments and find a new sigil for tags.

I propose `+` which was also my second proposal in #7.

#### Example

```properties
brand-name = Firefox
    +masculine

updated =
    { brand-name ->
        [masculine] { brand-name } został zaktualizowany.
        [feminine] { brand-name } została zaktualizowana.
       *[other] Program { brand-name } został zaktualizowany.
    }
```

**Comment by stasm** [comment]
AFAIK, there are no uses of tags in Mozilla projects right now.

**Comment by zbraniecki** [comment]
Is it a temporary measure until semantic comments, or a final proposal and you don't like the idea of using semantic comments for that?

**Comment by stasm** [comment]
I think we should discuss semantic comments in #16. My understanding of the scope of semantic comments is that they would be a place to put extra data available to tools rather than the runtime. In fact they wouldn't be parsed on runtime at all. This would make it impossible to use them for tags. (Let's continue in #16.)

**Comment by stasm** [comment]
We decided to replace tags with attributes defined on private messages. See #67 for discussion and #69 for implementation.
