### ISSUE TITLE
Syntax sugar for messages without value

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#71]
In #63 I'd like to make the `=` after the identifier required. 

```properties
foo-bar =
    .attr = Attribute Value
```

@zbraniecki suggested to also allow the syntax without the `=` as sugar.

```properties
foo-bar
    .attr = Attribute Value
```

I don't feel like this is an improvement or a convenience big enough to justify the syntax sugar. I'm not opposed to it _per se_, just not convinced at this point.

I'd like to suggest a different syntax shortcut, however. The following would parse as a `Message` with a null value and an `Attribute`.

```properties
foo-bar.attr = Attribute Value
```

This syntax sugar would only be available for writing messages with a single attribute. If more attributes are needed, the regular syntax would apply:

```properties
foo-bar =
    .attr1 = Attribute 1 Value
    .attr2 = Attribute 2 Value
```

My intention is to optimize the syntax for the common case of a message with a single attribute. The examples include HTML's `input` element or XUL's `key` element.

```properties
# Regular syntax.
username-input =
    .placeholder = Your username
open-file-command =
    .key = o

# Shorthand syntax.
username-input.placeholder = Your username
open-file-command.key = o
```

**Comment by Pike** [comment]
I think that `foo.bar = something` contradicts most of the arguments in favor of requiring the `=` in #63.

**Comment by stasm** [comment]
Why do you think that?

**Comment by Pike** [comment]
One of the big arguments was that it makes clear what the message ID is. And this syntax takes that away.

**Comment by stasm** [comment]
I disagree. The _key_ part is still clearly distinct from the value. (I'm using _key_ as a concept not an actual syntax construct.)

```properties
foo-bar.attr = Attribute
+----------+   +-------+
     key         value
```

**Comment by zbraniecki** [comment]
I disagree with stas. I believe that:

 * The `=` sign after the identifier with no value is not helping with readability
 * In fact, it does the opposite, it makes it harder to understand that the given message has no value
 * It removes the way to distinguish empty message from lack of message
 * It makes the Message with multiple attributes and no value (common case for WC/XUL) less readable and unnecessarily clunky

I believe that stas is justifying it with syntactic consistency and simplification for the parser, which I believe is the wrong tradeoff.

All feedback I got on 0.5 from syntax changes from people I asked indicates that this is not something people would like to see and they value the current model better.
In result I'd like to request the syntactic sugar to be added to avoid regressing the UX of working with Fluent in 0.5.

The proposal from stas for `id.attr = Value` is something I'd also like to see, and I believe it's the optimal UX, for cases with a single attribute and no value, or for cases with multiline value followed by an attribute. But I do not see it as a replacement for:

```
key
    .attr1 = Value
    .attr2 = Value 2
```

**Comment by zbraniecki** [comment]
> I'm not opposed to it per se, just not convinced at this point.

How do you want to approach it procedurally? I believe all stakeholders provided you feedback indicating that it is desired. On the other side, you're presenting your opinion as a project leader that "you're not convinced".
I'm not sure how to break a deadlock in such case.

**Comment by flodolo** [comment]
```properties
foo-bar =
    .attr = Attribute Value
```

I find this extremely confusing. I think that anyone reading the file should be able to mentally strip whitespaces, and still make sense of the syntax. This one reads like:

```properties
foo-bar = .attr = Attribute Value
```

Where the value of `foo-bar` is `.attr = Attribute Value`.

Regarding the other point:

```properties
foo-bar.attr = Attribute Value
```

I don't have a strong opinion against it, but I see Axel's point: it makes it look like the message ID is `foo-bar.attr`, not `foo-bar`. I also wonder if this would be a valid syntax at that point, or if the parser would complain about it:

```properties
foo-bar.label = Foo
foo-bar.accesskey = F
```

I totally see developers doing this, especially if they start with a value and add attributes later on. This sounds like a potential argument against allowing this form.

**Comment by stasm** [comment]
>  I also wonder if this would be a valid syntax at that point, or if the parser would complain about it:

```properties
foo-bar.label = Foo
foo-bar.accesskey = F
```

This is the same as:


```properties
foo-bar =
    .label = Foo
foo-bar =
    .accesskey = F
```

…which parses as two entries with the same identifier. `MessageContext` instances will only know about the last one.

**Comment by flodolo** [comment]
> …which parses as two entries with the same identifier. MessageContext instances will only know about the last one.

So, we would only know about the accesskey attribute? If that's the case, it seems like a strong argument against allowing that short syntax, unless we make sure we don't lose content.

**Comment by stasm** [comment]
Can this be solved with linting?

**Comment by stasm** [comment]
Replying to @zbraniecki's comment above:

> How do you want to approach it procedurally? I believe all stakeholders provided you feedback indicating that it is desired. On the other side, you're presenting your opinion as a project leader that "you're not convinced". I'm not sure how to break a deadlock in such case.

I don't know how to approach this. Let's figure out the process together!

I see the difference in opinions as a manifestation of different expectations from FTL.  Everyone comes into these discussions with a slightly different frame of mind and the idea behind what FTL should be. I'm looking at the [Design Principles](https://github.com/projectfluent/fluent/wiki/Design-Principles) to remind myself what the larger picture is, but I'll need a bit more time to process this.

**Comment by stasm** [comment]
I also understand my role as someone who's responsible for making sure the larger picture makes sense. This might sometimes be at odds with particular interests of other stakeholders who have their own agendas.

**Comment by flodolo** [comment]
At risk of pointing out the obvious: we have 4 FTL strings in Firefox 59, two of them fall into [this bucket](https://hg.mozilla.org/l10n/gecko-strings/file/default/browser/browser/preferences/preferences.ftl#l7), a lot more in the other patch for Preferences chrome.

What happens to 59 if we introduce `=` for empty values? Will we need to uplift the new version to Beta?

**Comment by stasm** [comment]
The discussion in #63 helped me make up my mind about syntax sugar in Fluent. Quoting https://github.com/projectfluent/fluent/issues/63#issuecomment-361618500:

> For the same reason of discoverability, going forward I will be likely against introducing any syntax sugar into the Fluent Syntax. Syntax sugar can save a few key strokes but for someone not familiar with the syntax it creates cognitive burden—it looks like something new which needs to be understood and learned independently. It's the simple vs. easy dilemma. Syntax sugar is easy to use once you know the underlying concepts, but it makes the syntax less simple by introducing complexity and choice.

I'm dismissing this proposal and closing this issue. Thanks for input!
