### ISSUE TITLE
Syntax for empty string value

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent#73]
Right now, there's no syntax for an empty string value, AFAICT.

One way to think about that would be to just use 

    my-text =

The other way is to try to create a non-"" AST value that evaluates to "". One candidate would be

    my-text = {""}

But that's also not allowed, 'cause `quote-text` is `'"' (text-char - '"' | '\"')+ '"'`, note the `+` instead of a `*`.

I didn't investigate what the fall-out of allowing `*` would be.

**Comment by stasm** [comment]
As I'd like to use the first form for all messages (#63), my preference (and an ongoing intent) has been to go for the second form. It has the benefit of being explicit and clearly visually distinctive, which I find helpful in this case. A zero-length value is an edge-case and I'd like to mark it visually as such.

**Comment by stasm** [comment]
#83 clarified the requirements for `quoted-text` making `{""}` legal. Regarding the null value, here's the summary of the rules as defined by Syntax 0.5.

```properties
# ERROR: messages must have values or attributes.
message =

# ERROR: terms must have values.
-term =
```

```properties
# OK: messages can have no values.
message =
    .attr = An attribute

# ERROR: terms must always have values.
-term =
    .attr = An attribute
```

```properties
# OK: both values here are empty strings (length == 0).
message = {""}
-term = {""}
```

```properties
# OK: variant values can also be empty strings.
message =
    { $num ->
        [zero] {""}
        [one] One something.
       *[other] Many somethings.
    }
```

**Comment by stasm** [comment]
I talked to @Pike and @zbraniecki about this and they agreed to use `{""}` to denote empty strings. Closing.

**Comment by langpavel** [comment]
`{""}` is terrible for translators — they are not programmers. I must study grammar what is possible/how should I write it down.
