### ISSUE TITLE
How to create new custom functions as the built in functions...?

### ISSUE THREAD

**Issue by fernandogmar** [projectfluent/fluent#78]
Hi again

I am trying to do this kind of function:
```
game_message = { FLAG($is_ready) ->
    *[inactive]  Insert coin
     [active]   Choose your hero
}
```
But no idea how to do it... I don't know how to get the `flag_value`:
```javascript
    const functions = {
        FLAG(flag_value) {
            return flag_value? 'active' : 'inactive';
        }
    };
    const mc = new MessageContext(config.locale, { functions });
```

**Comment by stasm** [comment]
_(Please file issues about the JavaScript implementation in https://github.com/projectfluent/fluent.js.)_

Fluent Functions, including custom builtins, take positional arguments as well as keyword arguments, which isn't supported by JavaScript out of the box. So instead, we make them accept two arguments: an array of positional args and an object keyword args.

See the example of `NUMBER` here: https://github.com/projectfluent/fluent.js/blob/dddb5db19bd5fc6a95a251cd7059cf26f187548d/fluent/src/builtins.js#L17

And here's the line which calls Functions: https://github.com/projectfluent/fluent.js/blob/dddb5db19bd5fc6a95a251cd7059cf26f187548d/fluent/src/resolver.js#L417

I think your example should work if you change the `FLAG` function as follows:

```js
// Destructure the array of positional arguments to flag_value.
FLAG([flag_value]) {
    return flag_value? 'active' : 'inactive';
}
```

**Comment by stasm** [comment]
BTW. this is a really nice usage of custom builtins!

**Comment by fernandogmar** [comment]
Thanks! 
I was having a look previously to NUMBER builtin... but I didn't get with the right answer :sweat_smile: And probably because I had to fix another issue first... 

So now your suggestion does the trick really well ;)
```javascript
// Destructure the array of positional arguments to flag_value.
FLAG([flag_value]) {
    return flag_value? 'active' : 'inactive';
}
 ``` 
Thanks again for your fast answer ;) I will post anything related with the implementation on fluent.js next time  ;)

**Comment by stasm** [comment]
I'm happy I was able to help!
